export const PROJECTS = [
  {
    title: "RUGShare",
    label: "Rug Sharing Platform",
    year: "2025/2026",
    role: "UI/UX + Dev",
    desc: "A platform that enables users to generate and share rug designs across digital and print media through customizable links and social-ready content.",
    tags: ["ReactJS", "Figma", "Typescript", "Tailwind"],
    num: "01",
    wide: false,
    url: "https://np.explorug.com/RUGShareV2/",
  },
  {
    title: "My Mosaic",
    label: "Image to Mosaic Tool",
    year: "2024/2025",
    role: "UI/UX + Dev",
    desc: "An interactive platform that reimagines images as detailed mosaics, where each fragment is recreated using unique rug and carpet designs to form a cohesive artwork.",
    tags: ["ReactJS", "Figma", "Typescript", "Tailwind"],
    num: "02",
    wide: true,
    url: "https://mymosaic.studio/",
  },
  {
    title: "Only1DollarDesigns",
    label: "Design Asset Platform",
    year: "2024",
    role: "UI/UX",
    desc: "Only1DollarDesign offers affordable, customizable and royalty-free designs for rugs and textile use. UI/UX crafted for clear navigation and effortless browsing.",
    tags: ["Figma"],
    num: "03",
    wide: false,
    url: "https://only1dollardesign.com/",
  },
  {
    title: "QaRt",
    label: "Custom QR Experience",
    year: "2024",
    role: "UI/UX",
    desc: "QaRt is a QR code generator that blends functionality with design. UI/UX crafted to make customization intuitive and visually engaging.",
    tags: ["Figma"],
    num: "04",
    wide: true,
    url: "https://myqart.studio/",
  },
  {
    title: "Ramro Designs",
    label: "Design Asset Platform",
    year: "2024",
    role: "UI/UX + Dev",
    desc: "Ramro Designs is a platform offering curated design collections for rugs, textiles, and interiors, complete with color-separated artwork and usage rights.",
    tags: ["ReactJS", "Figma", "JavaScript", "Tailwind"],
    num: "05",
    wide: false,
    url: "https://ramrodesigns.com/",
  },
];

export const SKILLS_DEV = [
  "HTML",
  "CSS",
  "Tailwind",
  "JavaScript",
  "TypeScript",
  "ReactJS",
];
export const SKILLS_DESIGN = [
  "Figma",
  "Design Systems",
  "Prototyping",
  "User Research",
  "Wireframing",
  "Galaincha",
];
